### ISSUE TITLE
Automate test to check that SPs asserting REFEDS R&S entity category meet technical requirements

### ISSUE THREAD

**Issue by alexstuart** [ukf/ukf-mda#17]
The technical requirements for this entity category that can be tested automatically are:

    4.3.1 The Service Provider [...] supports SAML V2.0 HTTP-POST binding.
    4.3.3 The Service Provider provides an mdui:DisplayName and mdui:InformationURL in metadata.
    4.3.4 The Service Provider provides one or more technical contacts in metadata.
    4.3.5 The Service Provider provides requested attributes in metadata.

https://refeds.org/category/research-and-scholarship/

**Comment by iay** [comment]
These are all testable using XSLT, so I'll close this here and get you to repost it on [`ukf/ukf-meta`](https://github.com/ukf/ukf-meta) if that's OK.
