### ISSUE TITLE
Add GitHub commit action to main branch

### ISSUE THREAD

**Issue by philsmart** [ukf/ukf-mda#24]
We want to port across the GitHub workflow/action from the maint-0.9 branch to the main branch: https://github.com/ukf/ukf-mda/blob/maint-0.9/.github/workflows/maven.yml

I am recording this as an issue at first, over a PR, to highlight the following changes:

- Java 11 support
- A change to the `on push` branch to `main`
- A change to the `on pull_request` branch to `main`
  - We may not want to the pipeline to run for each PR submitted? Although it gives quick feedback on the status of the unit tests.
- The artifact name loses the version number, we need to keep that.

**Comment by iay** [comment]
For what it's worth, I think having the action run on every PR submitted (or any subsequent push to a PR branch, or for that matter a push to any branch) is actually quite nice to have. The main downside is that it may chill pushing half-baked work, but I don't think we do a lot of that.

The main concern is to make sure that the right action is run for PRs hanging off the different branches (because of the version of Java used, for example).

I'm not sure the artifact name is very important in this case, if it's entirely local to the individual action run.

**Comment by philsmart** [comment]
Some initial investigations and doc reading:

1. ON
    1. [push] (without specifying a branch) is triggered by a **push** to **any** branch [1]. 
        - Added workflow with `on: [push]` to main branch, removed from maint-0.9 branch
            - Builds if there is a push to the main branch
            - Does **not** build if there is a push to the maint-0.9 branch
        - Added workflow with `on: [push]` to both main branch and maint-0.9 branch
            - Builds if there is a push to the main branch, using main branch workflow JDK11
            - Builds if there is a push to the maint-0.9 branch, using maint-0.9 branch workflow JDK8
    2. [push: branch: maint-0.9]
        - Added `on: push: to maint-0.9` to main branch, maint-0.9 has no actions.
            - Pushed to main branch, nothing built.
            - Pushed to maint-0.9 branch, nothing built.
    3. [push: branch: main/maint-0.9]
        - Added `on: push: main` to the main branch and `on: push: maint-0.9` to the maint-0.9 branch
            - Pushed to main branch, built with main workflow and JDK11
            - Pushed to maint-0.9 branch, built with maint-0.9 workflow and JDK8
        
        The behavior of (1.i) seems slightly different to what I would have expected from that documented [1]. My expectation would be it would trigger the action on **push** to **any** branch, but it does not. This is supported by this GitHub community answer [2]: only the workflows that exist on a branch are triggered by updates to that branch.

[1] [https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#understanding-the-workflow-file](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#understanding-the-workflow-file)

[2] [https://github.community/t/github-action-trigger-a-workflow-from-another-branch/120770](https://github.community/t/github-action-trigger-a-workflow-from-another-branch/120770)

**Comment by philsmart** [comment]
I furthered this by adding a Java 11 build action to my fork's main branch, alongside a Java 8 action on my maint-0.9 branch. 

- A PR for merging into main ran the correct Java 11 job (and only the Java 11 job)
- A PR for merging into maint-0.9 ran the correct Java 8 job (and only the Java 8 job)

@iay should we discuss adding such an action to the main branch?

**Comment by iay** [comment]
>only the workflows that exist on a branch are triggered by updates to that branch

That certainly makes _sense_, and provides us with a simple mental model. It isn't how I had interpreted the documentation up until now, which is why I was wary.

I think you should go ahead and add the action to the `main` branch on that basis.

**Comment by philsmart** [comment]
I agree that the documentation is not clear on this. I will make a PR.

**Comment by philsmart** [comment]
Action is in place.
