### ISSUE TITLE
Purge Eclipse files from the repository

### ISSUE THREAD

**Issue by iay** [ukf/ukf-mda#26]
For historical reasons related to how the Shibboleth project used to do things, this repository includes `.project` and `.classpath` files, plus a `.settings` directory representing Eclipse's idea that it is an Eclipse Java project.

Keeping these around causes problems if you use a different version of Eclipse or some other tool (such as Visual Studio Code) that shares state files.

The correct approach is for those files to be _ignored_ by Git. This means adding them to `.gitignore` but also removing them explicitly using `git rm`. This is the approach the Shibboleth project now takes to this issue, and I would like to replicate it here.

This will remove them from clones. If those clones are used by people in Eclipse, they will need to be re-imported as Eclipse projects, giving them a new `.project` file which may or may not be similar to the old one. However, because of the `.gitignore` entry, that new file will _not_ be suggested as a change to be re-committed.

**Comment by philsmart** [comment]
Those should be purged for the two branches in the PRs. I tested an import back into Eclipse. The new project files etc. are created and ignored correctly by Git.
